### ISSUE TITLE
If 'InputDevice' isn't about the device itself, but about its capabilities, rename the interface?

### ISSUE THREAD

**Issue by smaug----** [WICG/input-device-capabilities#19]
If 'InputDevice' isn't about the device itself, but about its capabilities, should the interface be renamed?
Like InputDeviceCapabilities and then UIEvent could have something like
InputDeviceCapabilities? sourceCapabilities = null;

This way one doesn't immediately expect the interface to have something like
readonly attribute DOMString type; // mouse, pen ...

**Comment by RByers** [comment]
The least 'capability-like' API [suggested in the brainstorming doc](https://docs.google.com/document/d/1WLadG2dn4vlCewOmUtUEoRsThiptC7Ox28CRmYUn8Uw/edit#heading=h.o7qaw089pyqp) is 'isCurrentlyOnScreen' (for virtual keyboards).  That's more like 'state' than 'capabilities', but seems pretty close.

So I'm OK with "InputDeviceCapabilities" and "sourceCapabilities" if that's the consensus.  @patrickhlauke @jacobrossi @garykac @tdresser @SummerWW any opinion?

**Comment by RByers** [comment]
Also +@mbrubeck since he contributed to the original design discussion here on the TECG call

**Comment by garykac** [comment]
DeviceCapabilities sounds good to me.

If we do that, I think that it makes sense to remove DeviceClass entirely.
That'll eliminate the problem of what to do about devices that fit into
multiple categories.

If something like the class is still desirable, then I'd prefer something
like hasKeyboardCapabilites, hasTouchScreenCapabilities, et al., since this
would allow devices to belong to multiple classes.

**Comment by patrickhlauke** [comment]
+1 to making the name less ambiguous and more about capabilities. if we do want something state-like (as in the keyboard example), maybe calling it characteristics, rather than capabilities, which would perhaps cover the second case as well?

**Comment by tdresser** [comment]
This approach also implies that testing equality isn't meaningful. Intuitively, I'd expect that if the `sourceDevice` of two events is the same, then they came from the same physical input device. I wouldn't assume this with `sourceCapabilities`.

LGTM!

**Comment by RByers** [comment]
Thanks everyone!

@garykac I don't think we can use `DeviceCapabilities` since there's already [a W3C spec](http://www.w3.org/2012/sysapps/device-capabilities/#devicecapabilities-interface) that uses that class name for system-wide capabilities.  `InputDeviceCapabilities` has some nice symmetry with that though.

So concrete proposal is:
- Rename `InputDevice` to `InputDeviceCapabilities`
- Rename `sourceDevice` to `sourceCapabilities`

Let's keep the discussion open for another day or two, then @SummerLW says she will do the renames (spec, polyfill, tests, and blink implementation).

**Comment by RByers** [comment]
Done
